### ISSUE TITLE
Automatic addition of import breaks when a file comment is present

### ISSUE THREAD

**Issue by z0u** [keskiju/autocomplete-java#42] opened 2016-05-18 01:43 UTC
Sometimes when autocompleting a type that requires a new import, the entire list of imports is moved into the file comment header. For example, given a class like this:

``` java
/*
 * This file is part of Foo.
 */

package org.bar;

import java.util.List;

public class Foo {
    public List<Integer> getList() {
        return null;
    }
}
```

Trying to autocomplete `ArrayList` in the method `getList` would move all the imports into the comment like so:

``` java
/*

import java.util.ArrayList;
import java.util.List;
 * This file is part of Foo.
 */

package org.bar;

public class Foo {
    public List<Integer> getList() {
        return new ArrayList();
    }
}
```

... Actually it doesn't happen for that simple example (ArrayList is not imported at all for some reason in my test file). But it does happen when I edit a [larger file](https://github.com/vpac-innovations/rsa/blob/006252fb2232a8d53a125de641ea237e79eb2754/src/storagemanager/src/main/java/org/vpac/ndg/storage/dao/ArrayType.java).

**Comment by keskiju** [comment] 2016-05-18 06:52
Caused by #35.

**Comment by keskiju** [comment] 2016-08-08 16:00
duplicate of #35

**Closed as completed by keskiju** 2016-08-08 16:00 UTC
