### ISSUE TITLE
Search in ignoring some possible matches

### ISSUE THREAD

**Issue by RomuloPBenedetti** [keskiju/autocomplete-java#21] opened 2016-01-02 05:28 UTC
An example is Duration class:

![delet5](https://cloud.githubusercontent.com/assets/12467382/12073319/533235de-b100-11e5-9837-9298a98fe80c.png)

I can find JavaFX packages in general, but some classes conflict, I believe search should show all variations of the class.

**Comment by keskiju** [comment] 2016-01-06 16:51
When there are many classes with the same name in classpath, you'll have to make a more detailed query to find the correct class. Currently only way to do that is to write the whole package name from the beginning (e.g. "javafx.util.D") but once fuzzy search has been implemented (issue #11), you can write just parts of the class and package name to find the correct class (e.g. "Dura.fx").

I made autocomplete suggesstions a little bit smarter in v0.10.1 release. Hopefully most of the time the autocomplete will suggest correct class even when there are multiple classes with the same name in classpath. And therefore, hopefully, no need for fuzzy search most of the time.

**Comment by keskiju** [comment] 2016-01-08 15:33
Duplicate of #11

**Closed as completed by keskiju** 2016-01-08 15:33 UTC
